

spring:
  ##数据库连接信息
  datasource:
    url: jdbc:mysql://192.168.43.110:3306/demo
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
    ###################以下为druid增加的配置###########################
    druid:
      db-type: mysql
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
  redis:
    database: 0
    host: 192.168.43.110
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
  data:
    elasticsearch:
      client:
        reactive:
          username:
          password:
          socket-timeout: 3000
          endpoints: 192.168.43.110:9200
          use-ssl: false
          connection-timeout: 3000
      repositories:
        enabled: true
  elasticsearch:
    rest:
      uris: 192.168.43.110:9200

sharding:
  jdbc:
    datasource:
      names: master0,master1
      master0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.43.110:3306/master0
        username: root
        password: 123123
      master1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.43.110:3306/master1
        username: root
        password: 123123
    config:
      props:
        sql.show: true
      sharding:
        default-database-strategy:
          inline:
            sharding-column: sex
            algorithm-expression: master$->{sex % 2}
        tables:
          user_info:
            actual-data-nodes: master$->{0..1}.user_info$->{0..1}
            table-strategy:
              inline:
                sharding-column: sex
                algorithm-expression: user_info$->{sex % 2}

      masterslave:
        name: ms
        load-balance-algorithm-type: round_robin
        slave-data-source-names: master0,master1



mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.entity
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
      table-underline: true





